"use cache";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Suspense } from "react";
import { InvalidateButton } from "./components/invalidate-button";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Rendered RootLayout");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-2">
          <Suspense>
            <InvalidateButton method="revalidateTag" tag="tag" />
            <InvalidateButton method="updateTag" tag="tag" />
          </Suspense>
        </nav>
        <NuqsAdapter>{children}</NuqsAdapter>
      </body>
    </html>
  );
}
